### ISSUE TITLE
Ошибка создания Board

### ISSUE THREAD

**Issue by maksumov** [NexGenUA/nodejs-course-frontend#1]
# Краткое резюме

При попытке создания Board UI выдаёт ошибку. Скорее всего оформлен неверный запрос к API:

- Метод `OPTIONS` вместо `POST`
- не передаётся title в теле запроса
- возможно также нужно адресовать запрос на `/boards` вместо `/boards/`

## Ожидание

В API прилетает запрос `POST /boards`.
В `req.body` есть `title` с наименованием создаваемой доски.

## Реальность

В API прилетает запрос `OPTIONS /boards/`.
В `req.body` при этом ничего нет.

**Comment by NexGenUA** [comment]
Приложение отдает правильные `headers`? В `README.md` есть небольшая инструкция по настройке `cors`

**Comment by maksumov** [comment]
Cors не настраивал. После настройки CORS приложение заработало.
